[binaries]
c = 'emcc'
cpp = 'em++'
ar = 'emar'
strip = 'emstrip'
exe_wrapper = 'node'
pkg-config = 'pkg-config'

[properties]
needs_exe_wrapper = true
skip_sanity_check = true
longdouble_format = 'IEEE_QUAD_LE'

[host_machine]
system = 'emscripten'
cpu_family = 'wasm32'
cpu = 'wasm'
endian = 'little'

[built-in options]
default_library = 'static'
# Flags for Emscripten compilation:
# - sALLOW_MEMORY_GROWTH=1 allows the heap to grow beyond the initial size
# - sSTACK_SIZE=8MB increases the stack size to 8 MB. The default is 64 KB
#   which is too small for large local arrays used in routines.
# - sINITIAL_MEMORY=64MB sets the initial memory size to 64 MB
# - sEXIT_RUNTIME makes the process exit code track CMocka's return value so
#   that meson test can tell pass from fail
# - sNODE_HOST_ENV is used to expose the host OS environment variables to
#   the compiled WASM module. We use it such that CMocka can see the
#   CMOCKA_MESSAGE_OUTPUT=TAP environment variable.
c_link_args = ['-sALLOW_MEMORY_GROWTH=1', '-sSTACK_SIZE=8MB', '-sINITIAL_MEMORY=64MB', '-sEXIT_RUNTIME=1', '-sNODE_HOST_ENV=1']
cpp_link_args = ['-sALLOW_MEMORY_GROWTH=1', '-sSTACK_SIZE=8MB', '-sINITIAL_MEMORY=64MB', '-sEXIT_RUNTIME=1', '-sNODE_HOST_ENV=1']
